#! /usr/bin/env node

const ora = require('ora')
const path = require('path')
const meow = require('meow')
const process = require('child_process').exec
const chokidar = require('chokidar')

const spinner = ora('Please wait').start()

const CLI = meow(`
  Usage
    $ gcx <filename>
  
  Options
    --silent, -s Hide compiling progress

  Example
    $ gcx example.cpp
`, {
  flags: {
    'silent': {
      type: 'boolean',
      alias: 's'
    }
  }
})

const compile = (file, verbose) => {
  return new Promise((resolve, reject) => {
    process(
      `g++ ${file} -o ${file.replace('cpp', 'out')} -lcurses && ./${file.replace('cpp', 'out')}`
    , (err, stdout, stderr) => {
      if (err) {
        reject(stderr)
      } else {
        resolve(stdout)
      }
    })
  })
}

if (CLI.input.length === 0) {
  CLI.showHelp()
}

else if (CLI.input.length > 1) {
  console.log('only can compile one file')
}

else {
  const filename = CLI.input[0]

  chokidar.watch(path.resolve(filename), {
    ignored: /(^|[\/\\])\../}
  ).on('all', (event, path) => {
    compile(filename, CLI.flags['silent'])
      .then(res => {
        console.log(res)
      })
      .catch(res => {
        console.log('error', res)
      })
  })
}
